<header>
    <h1>ITJobFinder</h1>
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply Now</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="admin.php">Manage</a></li>
        </ul>
    </nav>
</header>